monsterborg:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  monsterborg_velocity_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: ['base_to_lb_wheel', 'base_to_lf_wheel']
    right_wheel: ['base_to_rb_wheel', 'base_to_rf_wheel']
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    cmd_vel_timeout: 0.25
